/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface RewardVaultInterface extends Interface {
    getFunction(nameOrSignature: "calculateShare" | "claimReward" | "claimed" | "deposit" | "finalizeWave" | "owner" | "renounceOwnership" | "resetWave" | "rewardToken" | "setWaveAdmin" | "totalPointsAwarded" | "totalWavePool" | "transferOwnership" | "waveAdmin" | "waveFinalized"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "RewardClaimed" | "WaveAdminUpdated" | "WaveFinalized"): EventFragment;

    encodeFunctionData(functionFragment: 'calculateShare', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimReward', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'finalizeWave', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'resetWave', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'setWaveAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalPointsAwarded', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalWavePool', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'waveAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'waveFinalized', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'calculateShare', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeWave', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resetWave', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWaveAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalPointsAwarded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalWavePool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'waveAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'waveFinalized', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardClaimedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WaveAdminUpdatedEvent {
      export type InputTuple = [newAdmin: AddressLike];
      export type OutputTuple = [newAdmin: string];
      export interface OutputObject {newAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WaveFinalizedEvent {
      export type InputTuple = [totalPool: BigNumberish, totalPoints: BigNumberish];
      export type OutputTuple = [totalPool: bigint, totalPoints: bigint];
      export interface OutputObject {totalPool: bigint, totalPoints: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RewardVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): RewardVault;
    waitForDeployment(): Promise<this>;

    interface: RewardVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    calculateShare: TypedContractMethod<
      [_userPoints: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    claimReward: TypedContractMethod<
      [_user: AddressLike, _userPoints: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimed: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    finalizeWave: TypedContractMethod<
      [_totalPoints: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    resetWave: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rewardToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setWaveAdmin: TypedContractMethod<
      [_newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalPointsAwarded: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalWavePool: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    waveAdmin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    waveFinalized: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'calculateShare'): TypedContractMethod<
      [_userPoints: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claimReward'): TypedContractMethod<
      [_user: AddressLike, _userPoints: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalizeWave'): TypedContractMethod<
      [_totalPoints: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resetWave'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setWaveAdmin'): TypedContractMethod<
      [_newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalPointsAwarded'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalWavePool'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'waveAdmin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'waveFinalized'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RewardClaimed'): TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
getEvent(key: 'WaveAdminUpdated'): TypedContractEvent<WaveAdminUpdatedEvent.InputTuple, WaveAdminUpdatedEvent.OutputTuple, WaveAdminUpdatedEvent.OutputObject>;
getEvent(key: 'WaveFinalized'): TypedContractEvent<WaveFinalizedEvent.InputTuple, WaveFinalizedEvent.OutputTuple, WaveFinalizedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RewardClaimed(address,uint256)': TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
      RewardClaimed: TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
    

      'WaveAdminUpdated(address)': TypedContractEvent<WaveAdminUpdatedEvent.InputTuple, WaveAdminUpdatedEvent.OutputTuple, WaveAdminUpdatedEvent.OutputObject>;
      WaveAdminUpdated: TypedContractEvent<WaveAdminUpdatedEvent.InputTuple, WaveAdminUpdatedEvent.OutputTuple, WaveAdminUpdatedEvent.OutputObject>;
    

      'WaveFinalized(uint256,uint256)': TypedContractEvent<WaveFinalizedEvent.InputTuple, WaveFinalizedEvent.OutputTuple, WaveFinalizedEvent.OutputObject>;
      WaveFinalized: TypedContractEvent<WaveFinalizedEvent.InputTuple, WaveFinalizedEvent.OutputTuple, WaveFinalizedEvent.OutputObject>;
    
    };
  }